name: Bandit Security Scan

on:
  push:
  pull_request:

jobs:
  bandit:
    name: Run Bandit Security Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run Bandit Scan
        uses: shundor/bandit-action@v1
        with:
          path: "."
          level: high
          confidence: high
          exit_zero: true
